version: '3.8'

services:
  db:
    image: mysql:5.7
    # restart: always
    environment:
      MYSQL_DATABASE: "zssn_db"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "strong_password"
      MYSQL_ROOT_PASSWORD: "strong_root_password"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./zssn_backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./zssn_backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      MYSQL_DATABASE: "zssn_db"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "strong_password"
      MYSQL_HOST: db
      MYSQL_PORT: 3306

  frontend:
    build:
      context: ./zssn_frontend
    ports:
      - "8080:8080"
    volumes:
      - .:/zssn_frontend/src/app
      - /zssn_frontend/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  db_data: