# Generated by Django 3.2.25 on 2024-07-16 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('item_name', models.CharField(max_length=100)),
                ('item_quantity', models.IntegerField()),
                ('item_point', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Survivor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_infected', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('last_location_latitude', models.FloatField()),
                ('last_location_longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('item_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_outgoing', to='api.inventory')),
                ('item_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_incoming', to='api.inventory')),
                ('survivor_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_made', to='api.survivor')),
                ('survivor_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_received', to='api.survivor')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='survivor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.survivor'),
        ),
    ]
