# Generated by Django 3.2.25 on 2024-07-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_survivor_infected_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='item_point',
        ),
        migrations.AddField(
            model_name='inventory',
            name='item_quantity_blocked',
            field=models.IntegerField(default=0),
        ),
    ]
