# Generated by Django 3.2.25 on 2024-07-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20240720_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPrices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('item_price', models.IntegerField(default=0)),
            ],
        ),
    ]
