# Generated by Django 3.2.25 on 2024-07-20 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_itemprices'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeOffer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('totalPrice', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('receiverID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_offers_received', to='api.survivor')),
                ('requesterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_offers_made', to='api.survivor')),
            ],
        ),
        migrations.CreateModel(
            name='TradeOfferItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('item_quantity', models.IntegerField()),
                ('SurvivorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_offer_items', to='api.survivor')),
                ('TradeOfferId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_offer_items', to='api.tradeoffer')),
            ],
        ),
        migrations.DeleteModel(
            name='Trade',
        ),
    ]
