# Generated by Django 3.2.25 on 2024-07-21 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20240720_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradeoffer',
            old_name='receiverID',
            new_name='receiverId',
        ),
        migrations.RenameField(
            model_name='tradeoffer',
            old_name='requesterID',
            new_name='requesterId',
        ),
    ]
