# Generated by Django 3.2.25 on 2024-07-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20240721_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='survivor',
            name='reported_by',
            field=models.ManyToManyField(blank=True, related_name='reporter', to='api.Survivor'),
        ),
    ]
