# Generated by Django 3.2.25 on 2024-07-22 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_survivor_reported_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemPrices',
        ),
    ]
